server:
  port: ${SERVER_PORT:8091}

spring:
  application:
    name: ms-movimientos
  datasource:
    url: jdbc:h2:mem:msmovimientos;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        spring.json.add.type.headers: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
app:
  kafka:
    topics:
      movimiento-registrado: movimiento-registrado
logging:
  level:
    com.duocuc.bankbff: INFO
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

