server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: bff-atm
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bank_batch}
    username: ${DB_USER:bank_batch}
    password: ${DB_PASSWORD:bank_batch}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

security:
  jwt:
    secret: ${ATM_JWT_SECRET:atm-bff-secreto-distinto-y-mas-critico-0003}
    issuer: bff-atm
    expiration-minutes: ${ATM_JWT_EXP_MIN:15}
  atm:
    api-key: ${ATM_DEVICE_API_KEY:atm-device-key-demo-cambiar}

logging:
  level:
    com.duocuc.bankbff: INFO
    org.springframework.security: DEBUG

backend:
  oauth:
    token-url: http://localhost:9000/oauth2/token
    client-id: bff-atm-client
    client-secret: atm-secret-2026
    scope: cuentas.read cuentas.write movimientos.write
  ms-cuentas:
    base-url: http://localhost:8090
  ms-movimientos:
    base-url: http://localhost:8091
  ms-transacciones:
    base-url: http://localhost:8092
resilience4j:
  circuitbreaker:
    instances:
      msCuentas:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
  retry:
    instances:
      msCuentas:
        max-attempts: 3
        wait-duration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers
  health:
    circuitbreakers:
      enabled: true